version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker ps -a
      - run: sudo apt install curl
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: 
          working_directory: ~/project/API
          command: npm install
      - run: 
          working_directory: ~/project/API
          command: npm run test